timeout: '18000s'

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:
  - id: INIT-BUILDX
    name: gcr.io/cloud-builders/docker:24.0.9
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker run --privileged gcr.io/teknoir/binfmt-qemu:v0.8-v7.0.0
        docker buildx create --name teknoirmultiarchbuilder --use
        docker buildx inspect --bootstrap
    waitFor: ['-']

  - id: BUILD-BASE-IMAGE
    name: gcr.io/cloud-builders/docker:24.0.9
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        ./docker-buildx build \
          --builder teknoirmultiarchbuilder \
          --platform=linux/amd64,linux/arm64 \
          --push \
          --label "git-commit=${SHORT_SHA}" \
          --annotation 'index:github.com/project-slug=teknoir/yolov7_app' \
          --annotation 'index:teknoir.org/display-name=yolov7-base' \
          --annotation 'index:teknoir.org/description="Yolo v7 CPU base image."' \
          --annotation 'index:teknoir.org/framework=pythorch' \
          -t us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-base:${BRANCH_NAME}-cpu-${SHORT_SHA} \
          -f cpu.Dockerfile .
        
        if [ ${BRANCH_NAME} == 'main' ]; then
          ./docker-buildx build \
            --builder teknoirmultiarchbuilder \
            --platform=linux/amd64,linux/arm64 \
            --push \
            --annotation 'index:github.com/project-slug=teknoir/yolov7_app' \
            --annotation 'index:teknoir.org/display-name=yolov7-base' \
            --annotation 'index:teknoir.org/description="Yolo v7 CPU base image."' \
            --annotation 'index:teknoir.org/framework=pythorch' \
            --label "git-commit=${SHORT_SHA}" \
            -t us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-base:cpu-latest \
            -f cpu.Dockerfile .
        fi
    waitFor: ['INIT-BUILDX']

  - id: DL_COCO_NAMES
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'coco.names', 'https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names']
    waitFor: ['-']

  - id: DL_YOLOV7_TINY_PT
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'yolov7-tiny.pt', 'https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt']
    waitFor: ['-']

  - id: BUILD-VANILLA-IMAGE-EXAMPLE
    name: gcr.io/cloud-builders/docker:24.0.9
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BRANCH_NAME=${BRANCH_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        ./docker-buildx build \
          --builder teknoirmultiarchbuilder \
          --build-arg=BASE_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-base:${BRANCH_NAME}-cpu-${SHORT_SHA} \
          --build-arg=MODEL_NAME=yolov7 \
          --build-arg=TRAINING_DATASET=coco \
          --build-arg=IMG_SIZE=640 \
          --build-arg=WEIGHTS_FILE=yolov7-tiny.pt \
          --build-arg=CLASS_NAMES_FILE=coco.names \
          --platform=linux/amd64,linux/arm64 \
          --push \
          --annotation 'index:teknoir.org/display-name=yolov7-vanilla' \
          --annotation 'index:teknoir.org/description="Yolo v7 CPU vanilla."' \
          --annotation 'index:teknoir.org/framework=pythorch' \
          --annotation 'index:teknoir.org/image-type=model' \
          --annotation 'index:teknoir.org/model-type-description=yolov7' \
          --annotation 'index:teknoir.org/model-name=vanilla' \
          --annotation 'index:teknoir.org/model-dataset=coco' \
          --annotation 'index:teknoir.org/version=v1.0.0' \
          --annotation 'index:teknoir.org/model-feature=cpu' \
          --label "git-commit=${SHORT_SHA}" \
          -t us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-vanilla:${BRANCH_NAME}-cpu-${SHORT_SHA} \
          -f ./vanilla.Dockerfile .
        
        if [ ${BRANCH_NAME} == 'main' ]; then
          ./docker-buildx build \
            --builder teknoirmultiarchbuilder \
            --build-arg=BASE_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-base:${BRANCH_NAME}-cpu-${SHORT_SHA} \
            --build-arg=MODEL_NAME=yolov7 \
            --build-arg=TRAINING_DATASET=coco \
            --build-arg=IMG_SIZE=640 \
            --build-arg=WEIGHTS_FILE=yolov7-tiny.pt \
            --build-arg=CLASS_NAMES_FILE=coco.names \
            --platform=linux/amd64,linux/arm64 \
            --push \
            --annotation 'index:teknoir.org/display-name=yolov7-vanilla' \
            --annotation 'index:teknoir.org/description="Yolo v7 CPU vanilla."' \
            --annotation 'index:teknoir.org/framework=pythorch' \
            --annotation 'index:teknoir.org/image-type=model' \
            --annotation 'index:teknoir.org/model-type-description=yolov7' \
            --annotation 'index:teknoir.org/model-name=vanilla' \
            --annotation 'index:teknoir.org/model-dataset=coco' \
            --annotation 'index:teknoir.org/version=v1.0.0' \
            --annotation 'index:teknoir.org/model-feature=cpu' \
            --label "git-commit=${SHORT_SHA}" \
            -t us-central1-docker.pkg.dev/${PROJECT_ID}/teknoir-ai/yolov7-vanilla:cpu-latest \
            -f ./vanilla.Dockerfile .
        fi
    waitFor: ['BUILD-BASE-IMAGE', 'DL_COCO_NAMES', 'DL_YOLOV7_TINY_PT']
