timeout: '18000s'

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:
  - id: l4t_base
    name: gcr.io/teknoir/edgebuild
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BRANCH_NAME=${BRANCH_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
    waitFor: ['-']

  - id: initialize-buildx
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker run --privileged linuxkit/binfmt:v0.8-amd64
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
    waitFor: ['-']

  - id: amd64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker build \
          --push \
          -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-amd64-${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/yolov7:amd64 \
          .
    waitFor: ['-']

  - id: arm64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker buildx build \
          --platform=linux/arm64 \
          --push \
          -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-arm64-${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/yolov7:arm64 \
          .
    waitFor: ['initialize-buildx']

  - id: manifest
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker manifest create \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-amd64-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-arm64-${SHORT_SHA}

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-amd64-${SHORT_SHA} \
        --os=linux

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-arm64-${SHORT_SHA} \
        --os=linux \
        --arch=arm64 \
        --variant=v8

        docker manifest push gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-${SHORT_SHA}

        if [ ${BRANCH_NAME} == 'main' ]; then
          docker manifest create \
          gcr.io/${PROJECT_ID}/yolov7:latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-amd64-${SHORT_SHA} \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-arm64-${SHORT_SHA}

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-amd64-${SHORT_SHA} \
          --os=linux

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-arm64-${SHORT_SHA} \
          --os=linux \
          --arch=arm64 \
          --variant=v8

          docker manifest push gcr.io/${PROJECT_ID}/yolov7:latest
        fi
    waitFor:
      - amd64
      - arm64

  - id: nv-amd64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker build \
          --push \
          -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/yolov7:nv-amd64 \
          -f nv.Dockerfile .
    waitFor: ['-']

  - id: nv-arm64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker buildx build \
          --platform=linux/arm64 \
          --push \
          -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/yolov7:nv-arm64 \
          -f nv.Dockerfile .
    waitFor: ['initialize-buildx', 'arm64']

  - id: nv-manifest
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker manifest create \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA}

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
        --os=linux

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
        --os=linux \
        --arch=arm64 \
        --variant=v8

        docker manifest push gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA}

        if [ ${BRANCH_NAME} == 'main' ]; then
          docker manifest create \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA}

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
          --os=linux

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
          --os=linux \
          --arch=arm64 \
          --variant=v8

          docker manifest push gcr.io/${PROJECT_ID}/yolov7:nv-latest
        fi
    waitFor:
      - nv-amd64
      - nv-arm64

  - id: coco_names
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'coco.names', 'https://raw.githubusercontent.com/onnx/models/main/vision/object_detection_segmentation/yolov4/dependencies/coco.names']
    waitFor: ['-']

  - id: yolov4_pt
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'yolov7.pt', 'https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt']
    waitFor: ['-']

  - id: yolov7_vanilla
    name: gcr.io/cloud-builders/docker
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BRANCH_NAME=${BRANCH_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        ./build_vanilla.sh
    waitFor:
      - manifest
      - nv-manifest
      - coco_names
      - yolov4_pt

  - id: l4t_yolov7_vanilla
    name: gcr.io/cloud-builders/docker
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BRANCH_NAME=${BRANCH_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        ./build_l4t_vanilla.sh
    waitFor:
      - l4t_base
      - coco_names
      - yolov4_pt
      - yolov7_vanilla
