timeout: '18000s'

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled

steps:
  - id: initialize-buildx
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker run --privileged gcr.io/teknoir/binfmt-qemu:v0.8-v7.0.0
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
    waitFor: ['-']

  - id: classes_names
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'classes.names', 'https://raw.githubusercontent.com/onnx/models/main/vision/object_detection_segmentation/yolov4/dependencies/coco.names']
    waitFor: ['-']

  - id: yolov7_tiny_pt
    name: gcr.io/cloud-builders/wget
    args: ['-qO', 'yolov7-tiny.pt', 'https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt']
    waitFor: ['-']

  - id: nv-amd64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker build -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} -f nv.Dockerfile --label "git-commit=${SHORT_SHA}" .
        docker tag gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} gcr.io/${PROJECT_ID}/yolov7:nv-amd64
        docker push gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA}
        docker push gcr.io/${PROJECT_ID}/yolov7:nv-amd64
    waitFor: 
      - 'initialize-buildx'
      - yolov7_tiny_pt
      - classes_names

  - id: nv-arm64
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker buildx build \
          --platform=linux/arm64 \
          --push \
          --label "git-commit=${SHORT_SHA}" \
          -t gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/yolov7:nv-arm64 \
          -f nv.Dockerfile .
    waitFor: 
      - 'initialize-buildx'
      - yolov7_tiny_pt
      - classes_names
      
  - id: nv-manifest
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        docker manifest create \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA}

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
        --os=linux

        docker manifest annotate \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA} \
        gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
        --os=linux \
        --arch=arm64 \
        --variant=v8

        docker manifest push gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-${SHORT_SHA}

        if [ ${BRANCH_NAME} == 'main' ]; then
          docker manifest create \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA}

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-amd64-${SHORT_SHA} \
          --os=linux

          docker manifest annotate \
          gcr.io/${PROJECT_ID}/yolov7:nv-latest \
          gcr.io/${PROJECT_ID}/yolov7:${BRANCH_NAME}-nv-arm64-${SHORT_SHA} \
          --os=linux \
          --arch=arm64 \
          --variant=v8

          docker manifest push gcr.io/${PROJECT_ID}/yolov7:nv-latest
        fi
    waitFor:
      - nv-amd64
      - nv-arm64

 
  - id: yolov7_vanilla
    name: gcr.io/cloud-builders/docker
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BRANCH_NAME=${BRANCH_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eo pipefail
        ./build_nv_vanilla.sh
    waitFor:
      - nv-manifest
      - yolov7_tiny_pt
      - classes_names