ARG BASE_IMAGE=gcr.io/teknoir/yolov7:l4tr32.7.1
FROM ${BASE_IMAGE}

ARG MODEL_NAME=yolov7-stack
ENV MODEL_NAME=$MODEL_NAME

ARG IMG_SIZE=416
ENV IMG_SIZE=$IMG_SIZE

ARG WEIGHTS_FILE
ENV WEIGHTS_FILE=$WEIGHTS_FILE
ENV WEIGHTS=/usr/src/app/yolov7-tiny.pt
ADD $WEIGHTS_FILE $WEIGHTS

ARG CLASS_NAMES_FILE
ENV CLASS_NAMES_FILE=$CLASS_NAMES_FILE
ENV CLASS_NAMES=/usr/src/app/coco.names
ADD $CLASS_NAMES_FILE $CLASS_NAMES

ADD app.py /usr/src/app/app.py
ADD tracker/ /usr/src/app/tracker/