site_name: yolov7_app
site_description: Documentation of Yolov7 App for the Teknoir platform
repo_url: https://github.com/teknoir/yolov7_app
edit_uri: edit/main/app/docs/images
docs_dir: './images'
nav:
  - Home: index.md
plugins:
  - techdocs-core
